#!/usr/bin/env python3
"""Regenerate the licensed, pinned VSOP87D Earth and IAU 1980 nutation tables.
This developer tool is never called by the app or normal builds.
"""
from pathlib import Path
import hashlib
import json
import re
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
REVISION = '71e16c942b143a1a5a067b6aab2d8532064704ae'
BASE = 'https://raw.githubusercontent.com/commenthol/astronomia/' + REVISION + '/'
# All supported instants (including the UTC guard band) have abs(VSOP tau) < 0.102.
MAX_TAU = 0.102
# Sum of omitted |amplitude| * MAX_TAU**power: radians for L/B, AU for R.
OMITTED_BUDGET = 1e-6

def fetch(path):
    return urllib.request.urlopen(BASE + path, timeout=30).read().decode()

def main():
    earth = fetch('data/vsop87Dearth.js')
    nutation = fetch('src/nutation.js')
    license_text = fetch('LICENSE')
    value = earth[earth.index('{'):earth.rindex('}') + 1]
    model = json.loads(re.sub(r'([A-Za-z]+):', r'"\1":', value))
    rows = nutation.split('const tab = [')[1].split('\n  ]')[0]
    nutation_terms = json.loads('[' + rows + ']')
    bounds = {}
    counts = {}
    for key in ['L', 'B', 'R']:
        ranked = sorted((abs(row[0]) * MAX_TAU ** int(power), power, index)
                        for power, terms in model[key].items() for index, row in enumerate(terms))
        omitted, removed = 0.0, set()
        for weight, power, index in ranked:
            if omitted + weight > OMITTED_BUDGET:
                break
            omitted += weight
            removed.add((power, index))
        model[key] = {power: [row for index, row in enumerate(terms) if (power, index) not in removed]
                      for power, terms in model[key].items()}
        bounds[key] = omitted
        counts[key] = sum(map(len, model[key].values()))
    header = ['// Generated by scripts/generate_solar_coefficients.py; do not hand-edit.',
              '// VSOP87D Earth coefficients and IAU 1980 nutation table from astronomia.',
              '// Copyright (c) 2013 Sonia Keys; Copyright (c) 2016 Commenthol. MIT license.',
              '// Full permission notice: licenses/astronomia-MIT.txt.',
              '// Source revision: ' + REVISION,
              '// Earth source SHA256: ' + hashlib.sha256(earth.encode()).hexdigest(),
              '// Nutation source SHA256: ' + hashlib.sha256(nutation.encode()).hexdigest(),
              '// Deterministic small-term omission, abs(tau) <= ' + str(MAX_TAU) + ' across the app date range.',
              '// L/B bounds are radians; R bound is AU. Bound is relative to the full source table.',
              '// Omitted absolute-amplitude sums: ' + json.dumps(bounds, sort_keys=True),
              '// Retained term counts: ' + json.dumps(counts, sort_keys=True),
              '', 'extension SolarEphemeris {']
    out = header
    for key, name in [('L', 'longitudeTerms'), ('B', 'latitudeTerms'), ('R', 'radiusTerms')]:
        out.append('    static let ' + name + ': [[Term]] = [')
        for n in sorted(model[key], key=int):
            out.append('        [ // power ' + n)
            for term in model[key][n]:
                out.append('            .init(' + ', '.join(repr(x) for x in term) + '),')
            out.append('        ],')
        out.append('    ]')
    out.append('    static let nutationTerms: [[Double]] = [')
    for row in nutation_terms:
        out.append('        [' + ', '.join(repr(x) for x in row) + '],')
    out += ['    ]', '}', '']
    (ROOT / 'packages/LightPlanCore/Sources/LightPlanCore/SolarCoefficients.swift').write_text('\n'.join(out))
    (ROOT / 'licenses/astronomia-MIT.txt').write_text(license_text)

if __name__ == '__main__':
    main()
